backend:
  name: github
  repo: busitech-ir-lux/busitech-ir-lux.github.io
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "resume"
    label: "Resume"
    files:
      - name: "main"
        label: "Resume Data"
        file: "src/content/resume.json"
        format: "json"
        fields:
          - { label: "Profile Image", name: "image", widget: "image", required: false}
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Location", name: "location", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Summary", name: "summary", widget: "text" }
          - label: "Social Links"
            name: "social"
            widget: "list"
            required: false
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
              - label: "Icon"
                name: "icon"
                widget: "select"
                options: ["linkedin", "github", "website", "youtube", "instagram", "x", "behance", "artstation", "telegram", "whatsapp", "sololearn"]
                required: true
          - label: "Skills"
            name: "skills"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Level (0-100)", name: "level", widget: "number" }
              - label: "Tags"
                name: "tags"
                widget: "list"
                field: { label: "Tag", name: "tag", widget: "string" }

          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - label: "Tags"
                name: "tags"
                widget: "list"
                field: { label: "Tag", name: "tag", widget: "string" }

          - label: "Experience"
            name: "experience"
            widget: "list"
            fields:
              - { label: "Company", name: "company", widget: "string" }
              - { label: "Role", name: "role", widget: "string" }
              - { label: "Start", name: "start", widget: "string" }
              - { label: "End", name: "end", widget: "string" }
              - label: "Bullets"
                name: "bullets"
                widget: "list"
                field: { label: "Bullet", name: "bullet", widget: "string" }
